[workspace]
authors = ["Thomas Vuillaume <thomas.vuillaume@lapp.in2p3.fr>"]
channels = ["conda-forge"]
name = "questionnaire_preschool"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
pandas = ">=2.3.3,<3"
seaborn = ">=0.13.2,<0.14"
jupyterlab = ">=4.5.1,<5"
folium = ">=0.20.0,<0.21"
marimo = ">=0.19.2,<0.20"
plotly = ">=6.5.1,<7"
wordcloud = ">=1.9.4,<2"
pillow = ">=12.1.0,<13"
